SELECT  CAR_ID , CAR_TYPE, ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN
USING(CAR_TYPE)
WHERE DURATION_TYPE ="30일 이상" 
      AND CAR_TYPE IN ("SUV", "세단") 
      AND CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
         WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
      )
      
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;