SELECT  FP.PRODUCT_ID, FP.PRODUCT_NAME , SUM(FO.AMOUNT) * FP.PRICE AS TOTAL_SALES
FROM FOOD_ORDER FO INNER JOIN FOOD_PRODUCT FP
USING (PRODUCT_ID)
WHERE DATE_FORMAT(FO.PRODUCE_DATE,"%Y-%m") = "2022-05"
GROUP BY FP.PRODUCT_ID
ORDER BY 3 DESC , 1